version: '2'
services:
    angularkatr-app:
        image: angularkatr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://angularkatr-mysql:3306/angularkatr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angularkatr-mysql:
        extends:
            file: mysql.yml
            service: angularkatr-mysql
